version: "3.4"

x-common-variables: &common-variables
  MYSQL_USER: root
  MYSQL_PASSWORD: topher123
  MYSQL_DATABASE: toptal
  REACT_APP_SERVER_PORT: 3010

services:
  mysql:
    image: mysql:5.7
    environment:
      <<: *common-variables
      MYSQL_HOST: localhost
      MYSQL_ROOT_PASSWORD: topher123
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./toptal-db/startup.sql:/docker-entrypoint-initdb.d/startup.sql
  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    links:
      - mysql:mysql
    ports:
      - 8080:80
    restart: always
  server:
    build: ./toptal-server
    depends_on:
      - mysql
    expose:
      - 3010
    environment:
      <<: *common-variables
      DB_HOST: mysql
    ports:
      - 3010:3010
    volumes:
      - ./toptal-server:/app
    links:
      - mysql
    command: node index.js
    restart: always
  client:
    build: ./toptal
    environment:
      <<: *common-variables
      NODE_PATH: src
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./toptal/src:/app/src
    links:
      - server
    command: npm run start
    restart: always
    stdin_open: true
